package com.itis.android_tasks.utils

object ParamsKey {
    const val APP_CONFIG: String = "APP_CONFIG"
    const val DARK_THEME: String = "THEME"
    const val DEFAULT_NOTIFICATION_CHANNEL_ID = "CHANNEL_ID_"
    const val DEFAULT_NOTIFICATION_CHANNEL_NAME = "CHANNEL_NAME_"
    const val INTENT_MAIN_REQUEST_CODE = 101
    const val INTENT_HOME_TOAST_REQUEST_CODE = 102
    const val INTENT_NOTIFICATION_SETTINGS_REQUEST_CODE = 103
    const val INTENT_KEY = "INTENT_KEY"
    const val INTENT_NOTIFICATION_SETTINGS_VALUE = "INTENT_NOTIFICATION_SETTINGS_VALUE"
    const val INTENT_HOME_TOAST_VALUE = "INTENT_HOME_TOAST_VALUE"
}
